name: Deploy Flask API

on:
  push:
    branches:
    - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev
        docker build -t europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/test1/test1:test_ml_image .
        docker push europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/test1/test1:test_ml_image
    - name: Deploy cloud run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud run deploy test1 \
        --region=europe-west9 \
        --image=europe-west9-docker.pkg.dev/deploymlappgcl/test1:test_ml_image \
        --platform="managed" \
        --quiet
